### ISSUE TITLE
Strip transparency from image

### ISSUE THREAD

**Issue by humansnotfish** [humansnotfish/AssetManager#2]
- [ ] Have a way to tell the program where images are located
- bottom / center etc

- [ ] Specify a common bounding box

-  Load Image by most common medium length
- [ ] If there is no transparency in boundaries, go up a bounding box
- [ ] If there is transparency, calculate new bounding box, crop and save

Nice to have:

- [ ] Read in first 5/10 images and output common bounding boxes

**Comment by MorganNesbitt** [comment]
In retrospect the bounding box idea actually was inefficient and made little sense. As you have to read the whole image at start anyways, so creating entire new buffers with SubImage was worse allocating more memory then it needed.

**Comment by MorganNesbitt** [comment]
Instead reading in an image, and iterating over columns/rows to find first instance of non-zero alpha pixels.
